#pragma once

#define TOAL_ITEMS_IN_GAME 20
#define ITEM_COUNT_MAX 3
enum ItemID
{
    ItemID_None = 0,
    // Items
    // Orchard
    ItemID_SpryBerry,
    ItemID_PineBark,
    ItemID_LilyStem,
    ItemID_RosePetal,
    // River
    ItemID_MossTuft,
    ItemID_WetLeaf,
    ItemID_SnakeSkin,
    ItemID_FishBones,
    // Graveyard
    ItemID_BoneDust,
    ItemID_BellFlower,
    // Potions
    // Orchard
    ItemID_LilyPotion,
    ItemID_Fortifier,
    ItemID_EasyRemedy,
    // River
    ItemID_GreenFlux,
    ItemID_SimpleWash,
    // Graveyard
    ItemID_LifeMana,
};

enum PersonID
{
    PersonID_None = 0,
    PersonID_Elsie = 1,
    PersonID_WitchNormal = 2,
    PersonID_WitchTrollBefore = 4,
    PersonID_WitchTrollAfter = 8,
    PersonID_WitchZombie = 16,
};

enum ExpressionID
{
    ExpressionID_None = 0,
    ExpressionID_Normal,
    ExpressionID_Smile,
    ExpressionID_Ecstatic,
    ExpressionID_Thinking,
    ExpressionID_Dreaming,
    ExpressionID_Sigh,
    ExpressionID_Surprised,
    ExpressionID_Reading,
};

enum SceneID
{
    SceneID_None = 0,
    // bank 1
    SceneID_Title,
    // bank ?
    SceneID_SaveLoad,
    SceneID_Home,
    SceneID_Path,
    SceneID_Orchard,
    SceneID_Orchard_Search,
    // SceneID_Orchard_Wait,
    SceneID_Orchard_Deliver,
    SceneID_River,
    SceneID_River_Search,
    // SceneID_River_Wait,
    SceneID_River_Deliver,
    SceneID_Graveyard,
    SceneID_Graveyard_Search,
    // SceneID_Graveyard_Wait,
    SceneID_Graveyard_Deliver,
    SceneID_Recipe,
    SceneID_Quest,
    SceneID_End,
    // Bag
    SceneID_Bag_1,
    SceneID_Bag_2,
    SceneID_Bag_3,
    // Craft
    SceneID_CraftFinished,
    SceneID_Craft_Potion_1,
    SceneID_Craft_Potion_2,
    SceneID_Craft_Potion_3,
    SceneID_Craft_Potion_4,
    SceneID_Craft_Potion_5,
    SceneID_Craft_Potion_6,
    // SceneID_Craft_Potion_7,
    // SceneID_Craft_Potion_8,
    // SceneID_Craft_Potion_9,
    // bank 2
    SceneID_IntroCutscene_1,
    SceneID_IntroCutscene_2,
    SceneID_IntroCutscene_3,
    SceneID_IntroCutscene_4,
    SceneID_IntroCutscene_5,
    SceneID_IntroCutscene_6,
    SceneID_IntroCutscene_7,
    SceneID_IntroCutscene_8,
    SceneID_IntroCutscene_9,
    SceneID_IntroCutscene_10,
    SceneID_IntroCutscene_11,
    SceneID_IntroCutscene_12,
    SceneID_IntroCutscene_13,
    SceneID_IntroCutscene_14,
    // cont, bank 3
    SceneID_IntroCutscene_c_1,
    SceneID_IntroCutscene_c_2,
    SceneID_IntroCutscene_c_3,
    SceneID_IntroCutscene_c_4,
    SceneID_IntroCutscene_c_5,
    SceneID_IntroCutscene_c_6,
    SceneID_IntroCutscene_c_7,
    SceneID_IntroCutscene_c_8,
    SceneID_IntroCutscene_c_9,
    SceneID_IntroCutscene_c_10,
    SceneID_IntroCutscene_c_11,
    SceneID_IntroCutscene_c_12,
    SceneID_IntroCutscene_c_13,
    SceneID_IntroCutscene_c_14,
    SceneID_IntroCutscene_c_15,
    SceneID_IntroCutscene_c_16,
    // first potion delivery
    SceneID_Orchard_Delivery_1,
    SceneID_Orchard_Delivery_2,
    SceneID_Orchard_Delivery_3,
    SceneID_Orchard_Delivery_4,
    SceneID_Orchard_Delivery_5,
    SceneID_Orchard_Delivery_6,
    SceneID_Orchard_Delivery_7,
    SceneID_Orchard_Delivery_8,
    SceneID_Orchard_Delivery_9,
    SceneID_Orchard_Delivery_10,
    SceneID_Orchard_Delivery_11,
    SceneID_Orchard_Delivery_12,
    SceneID_Orchard_Delivery_13,
    SceneID_Orchard_Delivery_14,
    SceneID_Orchard_Delivery_15,
    // second potion delivery
    SceneID_Orchard_Delivery_2_1,
    SceneID_Orchard_Delivery_2_2,
    SceneID_Orchard_Delivery_2_3,
    SceneID_Orchard_Delivery_2_4,
    SceneID_Orchard_Delivery_2_5,
    SceneID_Orchard_Delivery_2_6,
    SceneID_Orchard_Delivery_2_7,
    SceneID_Orchard_Delivery_2_8,
    SceneID_Orchard_Delivery_2_9,
    SceneID_Orchard_Delivery_2_10,
    SceneID_Orchard_Delivery_2_11,
    SceneID_Orchard_Delivery_2_12,
    SceneID_Orchard_Delivery_2_13,
    SceneID_Orchard_Delivery_2_14,
    SceneID_Orchard_Delivery_2_15,
    SceneID_Orchard_Delivery_2_16,
    // third potion deliver
    SceneID_Orchard_Delivery_3_1,
    SceneID_Orchard_Delivery_3_2,
    SceneID_Orchard_Delivery_3_3,
    SceneID_Orchard_Delivery_3_4,
    SceneID_Orchard_Delivery_3_5,
    SceneID_Orchard_Delivery_3_6,
    SceneID_Orchard_Delivery_3_7,
    SceneID_Orchard_Delivery_3_8,
    SceneID_Orchard_Delivery_3_9,
    SceneID_Orchard_Delivery_3_10,
    SceneID_Orchard_Delivery_3_11,
    SceneID_Orchard_Delivery_3_12,
    SceneID_Orchard_Delivery_3_13,
    SceneID_Orchard_Delivery_3_14,
    SceneID_Orchard_Delivery_3_15,
    SceneID_Orchard_Delivery_3_16,
    // river delivery 1
    SceneID_River_Delivery_1_1,
    SceneID_River_Delivery_1_2,
    SceneID_River_Delivery_1_3,
    SceneID_River_Delivery_1_4,
    SceneID_River_Delivery_1_5,
    SceneID_River_Delivery_1_6,
    SceneID_River_Delivery_1_7,
    SceneID_River_Delivery_1_8,
    SceneID_River_Delivery_1_9,
    SceneID_River_Delivery_1_10,
    SceneID_River_Delivery_1_11,
    SceneID_River_Delivery_1_12,
    SceneID_River_Delivery_1_13,
    // river delivery 2
    SceneID_River_Delivery_2_1,
    SceneID_River_Delivery_2_2,
    SceneID_River_Delivery_2_3,
    SceneID_River_Delivery_2_4,
    SceneID_River_Delivery_2_5,
    SceneID_River_Delivery_2_6,
    SceneID_River_Delivery_2_7,
    SceneID_River_Delivery_2_8,
    SceneID_River_Delivery_2_9,
    SceneID_River_Delivery_2_10,
    SceneID_River_Delivery_2_11,
    SceneID_River_Delivery_2_12,
    SceneID_River_Delivery_2_13,
    // graveyard delivery 1
    SceneID_Graveyard_Delivery_1_1,
    SceneID_Graveyard_Delivery_1_2,
    SceneID_Graveyard_Delivery_1_3,
    SceneID_Graveyard_Delivery_1_4,
    SceneID_Graveyard_Delivery_1_5,
    SceneID_Graveyard_Delivery_1_6,
    SceneID_Graveyard_Delivery_1_7,
    SceneID_Graveyard_Delivery_1_8,
    SceneID_Graveyard_Delivery_1_9,
    SceneID_Graveyard_Delivery_1_10,
    SceneID_Graveyard_Delivery_1_11,
    SceneID_Graveyard_Delivery_1_12,
    SceneID_Graveyard_Delivery_1_13,
    SceneID_Graveyard_Delivery_1_14,
    SceneID_Graveyard_Delivery_1_15,
};